apiVersion: 1

contactPoints:
  - orgId: 1
    name: "incident-responder-webhook"
    receivers:
      - uid: "responder-webhook-uid"
        type: "webhook"
        settings:
          url: "http://incident-response:8001/alerts"
          httpMethod: "POST"

policies:
  - orgId: 1
    receiver: "incident-responder-webhook"
    group_by: ["alertname", "endpoint"]
    group_wait: 2s
    group_interval: 5s
    repeat_interval: 1h

groups:
  - orgId: 1
    name: "OrderTrackerAlerts"
    folder: "Order Tracker"
    interval: 5s
    rules:
      - uid: "order-tracker-5xx-alert"
        title: "OrderTrackerHigh5xxErrors"
        condition: "B"
        data:
          - refId: "A"
            queryType: ""
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: "Prometheus"
            model:
              editorMode: "code"
              expr: "sum(increase(order_tracker_http_requests_total{status_code=~\"5..\"}[1m])) or vector(0)"
              instant: true
              range: false
              refId: "A"
          - refId: "B"
            queryType: ""
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: "-100"
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: "gt"
                  operator:
                    type: "and"
                  query:
                    params: ["A"]
                  reducer:
                    params: []
                    type: "last"
                  type: "query"
              datasource:
                type: "__expr__"
                uid: "-100"
              expression: "A"
              reducer: "last"
              refId: "B"
              type: "threshold"
        noDataState: "OK"
        execErrState: "OK"
        for: "0s"
        annotations:
          summary: "Server 5xx errors detected on Order Tracker"
          description: "High rate of HTTP 5xx errors observed on order endpoints"
          dashboard_url: "http://localhost:3000/d/order-tracker-overview"
        labels:
          severity: "critical"
          endpoint: "/api/orders"
